### ISSUE TITLE
Stop downloading at nnnnn serial number.

### ISSUE THREAD

**Issue by hakt0-r** [wryyl/interfacelift-scraper#6]
If I am to assume that the way this works is it starts to download in a descending order, latest to the oldest. 

In my folder I have got all the previous ones and all I want is to download everything after image serial number 03990 (03990_autumncapital_2560x1440.jpg).

Is this even possible?

**Comment by hakt0-r** [comment]
I am sure you'll hate me after this 😸

**Comment by benjaminheng** [comment]
The script works by loading every page for a particular resolution, checking if each image on the page already exists and if not, add it to the queue. There's typically between 200~400 pages to load, depending on the resolution selected. The downloads will occur in a separate thread while the pages are being loaded.

However this means that if you already have the majority of the images, then no images will be added to the download queue for each page request, so the bottleneck becomes the page requests rather than the downloading.

The obvious solution is to add an option to specify what number to stop at, but I don't want to clutter up the options too much. Trying to keep it simple :)

In the meantime I suggest just terminating the script once it starts skipping images if you know you already have all the subsequent images!

**Comment by hakt0-r** [comment]
can you have a "-- Skipped" label next to the already present image file. This way we know when the system has reached such a stage where I can terminate its execution.

**Comment by benjaminheng** [comment]
Sure!

**Comment by hakt0-r** [comment]
thanks. Great product. 😄
